tecnomarket/app/urls.py
from django.urls import path, include
from .views import home, contacto, galeria, agregar_producto, listar_productos, modificar_producto, eliminar_producto, registro, DescripcionViewset, ProductoViewset, error_facebook
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', DescripcionViewset)
router.register('marca', ProductoViewset)

urlpatterns = [
    path('', home, name="home"),
    path('galeria/', galeria, name="galeria"),
    path('contacto/', contacto, name="contacto"),
    path('agregar-producto/', agregar_producto, name="agregar_producto"),
    path('listar-productos/', listar_productos, name="listar_productos"),
    path('modificar-producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('registro/', registro, name="registro"),
    path('api/',include(router.urls)),
    path('error-facebook/' ,error_facebook, name="error_faccebook"),

]

tecnomarket/tecnomarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
   
]

if settings.DEBUG:
    urlpatterns += static(settings. MEDIA_URL, document_root=settings.MEDIA_ROOT)

tecnomarket/app/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre
    
    
class Descripcion(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Producto, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="descripciones",null=True)
    def __str__(self):
        return self.nombre

opciones_consulta = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]

]


class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    avisos = models.BooleanField()


    def __str__(self):
        return self.nombre 

tecnomarket/app/templates/app/producto/agregar.html
{% extends 'app/base.html '%}

{% block contenido %}

{% load crispy_forms_tags %}


<br><br>
        <div class="row">
            <div class="col-12 col-md-6 offset -md-3">

            <div class="card">
                <div class="card-body">
                    <h2>Nuevo producto</h2>
                    <hr>

                    <form action="" method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        {{ form | crispy }}

                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <input type="submit" value="Guardar" class="btn btn-primary">

                        </div>
                        

                    </form>
                    {{mensaje}}

            </div>
        </div>

    </div>
</div>

{% endblock %}

tecnomarket/app/templates/app/producto/listar.html
{% extends 'app/base.html '%}

{% block js %}
<script>
    function eliminarDescripcion(id) {
        Swal.fire({
            "title" : "Estas seguro?",
            "text"  : "Los cambios no se pueden deshacer",
            "icon"  : "question",
            "showCancelButton" : true,
            "cancelButtonText" : "Cancelar",
            "confirmButtonText" : "Aceptar",
            "reverseButtons" : true,
            "confirmButtonColor" : "#dc3545",
            "cancelButtonColor" : "#17a2b8"
        })
        .then(function(result) {
            if(result.isConfirmed){
                window.location.href = "/eliminar-producto/"+id+"/"
            }
        })
    }
</script>
{% endblock %}  

{% block contenido %}
{% load humanize%}

<br><br><br>
<div class="card">
    <div class="card-body">
        <h2>Listado de productos</h2>
        <hr>
        <table class="table table-striped table-hover table-responsive-sm">

            <tr>
        
                <th>Nombre</th>
                <th>Precio</th>
                <th>Producto</th>
                <th>Es nuevo?</th>
                <th>Opciones</th>
            </tr>
        
            {% for p in entity %}
        
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>{{ p.precio | intcomma }}</td>
                <td>{{ p.marca | title }}</td>
                <td>
                    {% if p.nuevo %}
                    SI
                    {% else %}
                    NO
                    {% endif %}
        
                </td>
                <td>
                    {% if perms.app.change_producto %}
                    <a href="{% url 'modificar_producto' p.id %}" class="btn btn-info btn-sm">Modificar</a>
                    {% endif %}
                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminarDescripcion({{ p.id }})" class="btn btn-danger btn-sm">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        
        </table>
        <hr>
        <div>
            {% include 'app/paginator.html' %}

        </div>
    </div>
</div>


{% endblock %}  

tecnomarket/app/templates/app/producto/modificar.html
{% extends 'app/base.html '%}

{% block contenido %}

{% load crispy_forms_tags %}


<br><br>
        <div class="row">
            <div class="col-12 col-md-6 offset -md-3">

            <div class="card">
                <div class="card-body">
                    <h2>Editar producto</h2>
                    <hr>

                    <form action="" method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        {{ form | crispy }}

                        <div class="d-flex justify-content-end">
                            <input type="reset" value="Cancelar" class="btn btn-secondary">
                            &nbsp;
                            <input type="submit" value="Editar" class="btn btn-primary">

                        </div>
                        

                    </form>
                    {{mensaje}}

            </div>
        </div>

    </div>
</div>

{% endblock %}