tecnomarket/app/urls.py
from django.urls import path, include
from .views import home, contacto, galeria, agregar_producto, listar_productos, modificar_producto, eliminar_producto, registro, DescripcionViewset, ProductoViewset, error_facebook
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', DescripcionViewset)
router.register('marca', ProductoViewset)

urlpatterns = [
    path('', home, name="home"),
    path('galeria/', galeria, name="galeria"),
    path('contacto/', contacto, name="contacto"),
    path('agregar-producto/', agregar_producto, name="agregar_producto"),
    path('listar-productos/', listar_productos, name="listar_productos"),
    path('modificar-producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('registro/', registro, name="registro"),
    path('api/',include(router.urls)),
    path('error-facebook/' ,error_facebook, name="error_faccebook"),

]

tecnomarket/tecnomarket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
   
]

if settings.DEBUG:
    urlpatterns += static(settings. MEDIA_URL, document_root=settings.MEDIA_ROOT)

tecnomarket/app/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre
    
    
class Descripcion(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Producto, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="descripciones",null=True)
    def __str__(self):
        return self.nombre

opciones_consulta = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]

]


class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    avisos = models.BooleanField()


    def __str__(self):
        return self.nombre 

tecnomarket/app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GANOAPP</title>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
    
    {% load static %}
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block css %} 
    {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/estilo2.css' %}">
    
</head>
<body>

    
    <header id="header">
        <br><br><br>

        <img class="menu" src="{% static 'app/img/menuiconwhite.png'%}" alt="menu" id="menu">
        <div class="contenedor_logo">
            <img  class="logo"  src="{% static 'app/img/ganoicon.png' %}" alt="logo">
        </div>

        <div>
            
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'home'%}"> <font color="black">Inicio</font>  </a>
                    </li>
                    <li>
                        <a href="{% url 'contacto'%}"><font color="black">Contacto</font></a>
                    </li>
                    <li><a href="{% url 'galeria'%}"><font color="black">Galería</font></a></li>
                    {% if perms.app.add_producto %}
                    <li>
                        <a href="{% url 'agregar_producto' %}"><font color="black">Agregar producto</font></a>
                    </li>
                    {% endif %}
                    {% if perms.app.view_producto %}
                    <li><a href="{% url 'listar_productos' %}"><font color="black">Lista de productos</font></a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                   
                    <li>
                        <a href="{% url 'logout'%}"><font color="black">Cerrar sesion</font></a>
                    </li>
                    <li>
                        <a href="#">{{ user.username }}</a>
                    </li>
                    <li>
                        {% for auth in backends.associated %}

                            {% if auth.provider == 'facebook' %}
                                <img src="{{ auth.extra_data.picture.data.url }}" alt="" width="50" height="50">
                            {% endif %}

                        {% endfor %} 
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login'%}"><font color="black">Iniciar sesion</font></a>
                    </li>
                    <li>
                        <a href="{% url 'registro'%}"><font color="black">Registrarse</font></a>
                    </li>
                    {% endif %}
                </ul>
            </nav>

        </div>

    </header>

    <div id="contenido">

        

        {% block contenido %}
        {% endblock %}

    </div>

    <br><br><br>
    
    <footer>
        <div class="marcas">
            <img src="{% static 'app/img/footer/face.png'%}" alt="facebook">
            <img src="{% static 'app/img/footer/dj.png'%}" alt="django">
            <img src="{% static 'app/img/footer/vscode.png'%}" alt="vscode">
            <img src="{% static 'app/img/footer/sena.png'%}" alt="sena">
            <img src="{% static 'app/img/footer/pr.png'%}" alt="python">
        </div>
        <div class="logo_footer">
            <img src="{% static 'app/img/ganoicon.png'%}" alt="logo">
        </div>
    </footer>
                 <p class="copyright text-muted"><center>Copyright &copy; 2022 | GANOAPP (Tecnologos ADSI)</center> </p>
     
    <script src="{% static 'app/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'app/js/clean-blog.min.js'%}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  
    <script src="{% static 'app/js/menu.js'%}"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% block mensajeria %}
    {% if messages %}

            {% for m in messages %}
                <script>

                    Swal.fire({
                        "title" : "Felicitaciones",
                        "text" : "{{m}}",
                        "icon" : "success"
                    })

                </script>
            {% endfor %}

    {% endif %}

    {% endblock %}
    {% block js %}
    {% endblock %}
</body>
</html>

tecnomarket/app/templates/app/contacto.html
{% extends 'app/base.html '%}

{% block contenido %}
{%  load crispy_forms_tags %}
<div id="contenido">
    <br>
    <br>  
<div class="row">
     
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>Contactanos!</h2>
        <hr>
        <form action="" class="" method="post">

            {% csrf_token %}
    
            {{ form | crispy }}
    
            <br>
            <div class="d-flex justify-content-end">
    
                <input type="reset" value="Cancelar" class="btn btn-secondary">
                &nbsp;
                <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
            </div>
    
        </form>
            {{mensaje}} 
            </div>
        </div>
        
    </div>
    
</div>    


    <table id="tablacontactos">
        
    </table>


</div>
{% endblock %}

tecnomarket/app/templates/app/galeria.html
{% extends 'app/base.html '%}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block contenido %}

<h2>Galería de Productos</h2>
<br><br>
<div class="galeria">
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda1.jpeg' %}"><img src="{% static 'app/img/tienda/tienda1.jpeg' %}"></a>
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda2.jpg'%}"><img src="{% static 'app/img/tienda/tienda2.jpg' %}"></a>
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda3.jpeg' %}"><img src="{% static 'app/img/tienda/tienda3.jpeg' %}"></a>
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda4.jpeg' %}"><img src="{% static 'app/img/tienda/tienda4.jpeg' %}"></a>    
</div>

{% endblock %}

tecnomarket/app/templates/app/home.html
{% extends 'app/base.html '%}

{% load static %}

{% block title %}Portada{% endblock %}

{% block background %}{% static 'app/img/Campo_1.jpg' %}{% endblock %}

{% block js %}
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
<script>
    $(document).ready(function() {
      $('.slider').bxSlider({
          mode: 'fade',//horizontal, vertical, fade
          auto: true,
          pause: 2000
      });
    });
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock %}

{% block contenido %}

{%load humanize %}
<h2>Productos</h2>
<div class="productos">

    {% for p in productos %}

<div class="producto">

    <div class="contenedor_producto">
        {% if p.imagen %}
        <img src="{{ p.imagen.url }}" alt="imagen producto">
        {% endif %}
        <div class="detalle">
            <h5>{{ p.marca | capfirst }}</h5>
            <h2>{{ p.nombre | title }}</h2>
            <h3>${{ p.precio | intcomma}}</h3>
        </div>

    </div>

</div>
{% endfor %}
</div>

{% endblock %}

tecnomarket/app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}